<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entities\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'vender', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'add_no', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'upd_no', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'deleted', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'addDate', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'updDate', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productScenarioId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productInquiryId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productTagId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productAttachment'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'vender', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'add_no', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'upd_no', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'deleted', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'addDate', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'updDate', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productScenarioId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productInquiryId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productTagId', '' . "\0" . 'App\\Entities\\Product' . "\0" . 'productAttachment'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getVender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVender', []);

        return parent::getVender();
    }

    /**
     * {@inheritDoc}
     */
    public function setVender($vender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVender', [$vender]);

        return parent::setVender($vender);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddNo', []);

        return parent::getAddNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddNo($add_no)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddNo', [$add_no]);

        return parent::setAddNo($add_no);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdNo', []);

        return parent::getUpdNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdNo($upd_no)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdNo', [$upd_no]);

        return parent::setUpdNo($upd_no);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddDate', []);

        return parent::getAddDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddDate($addDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddDate', [$addDate]);

        return parent::setAddDate($addDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdDate', []);

        return parent::getUpdDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdDate($updDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdDate', [$updDate]);

        return parent::setUpdDate($updDate);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductScenario(\App\Entities\ScenarioProduct $scenarioProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductScenario', [$scenarioProduct]);

        return parent::addProductScenario($scenarioProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductScenarioId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductScenarioId', []);

        return parent::getProductScenarioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductScenarioId($productScenarioId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductScenarioId', [$productScenarioId]);

        return parent::setProductScenarioId($productScenarioId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductInquiryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductInquiryId', []);

        return parent::getProductInquiryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductInquiryId($productInquiryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductInquiryId', [$productInquiryId]);

        return parent::setProductInquiryId($productInquiryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTagId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTagId', []);

        return parent::getProductTagId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTagIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTagIds', []);

        return parent::getProductTagIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTag', []);

        return parent::getProductTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductTagId($productTagId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductTagId', [$productTagId]);

        return parent::setProductTagId($productTagId);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductTags(\App\Entities\TagProduct $productTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductTags', [$productTag]);

        return parent::addProductTags($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductAttachment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductAttachment', []);

        return parent::getProductAttachment();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductAttachment($productAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductAttachment', [$productAttachment]);

        return parent::setProductAttachment($productAttachment);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductImage(\App\Entities\ProductAttachment $productAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductImage', [$productAttachment]);

        return parent::addProductImage($productAttachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductParent', []);

        return parent::getProductParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

}
